export enum Routes {
  home = '/',
  about = '/about',
  blog = '/blog',
  cart = '/cart',
  contact = '/contact',
  detail = '/detail',
  formulation = '/formulation',
  orders = '/orders',
  privacyPolicy = '/privacy-policy',
  products = '/products',
  profile = '/profile',
  quiz = '/quiz',
  signin = '/auth/sign-in',
  signup = '/auth/sign-up',
  termsAndConditions = '/terms-and-conditions',
}
