export enum Routes {
  home = '/',
  about = '/about',
  blog = '/blog',
  forgotPassword = '/auth/forgot-password',
  formulation = '/formulation',
  privacyPolicy = '/privacy-policy',
  profile = '/profile',
  quiz = '/quiz',
  recipes = '/recipes',
  resetPassword = '/auth/reset-password',
  signin = '/auth/sign-in',
  signup = '/auth/sign-up',
  termsAndConditions = '/terms-and-conditions',
}
