export enum Routes {
  home = '/',
  about = '/about',
  cart = '/cart',
  contact = '/contact',
  detail = '/detail/',
  formulation = '/formulation',
  orders = '/orders',
  products = '/products',
  privacyPolicy = '/privacy-policy',
  profile = '/profile',
  quiz = '/quiz',
  recipes = '/recipes',
  signin = '/auth/sign-in',
  signup = '/auth/sign-up',
  termsAndConditions = '/terms-and-conditions',
}
