import './globals.css'
import cn from 'classnames'
import { Inter } from 'next/font/google'

import Providers from 'utils/provider'

import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(inter.className, 'flex items-center flex-col')}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}
