import './globals.css'

import Providers from 'utils/provider'

import Header from './components/Header'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='flex items-center flex-col'>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}
