import './globals.css'

import { notFound } from 'next/navigation'
import { useLocale } from 'next-intl'

import Header from 'components/common/Header'
import Providers from 'utils/provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode
  params: {
    locale: string
  }
}) {
  const locale = useLocale()

  if (params.locale !== locale) {
    notFound()
  }

  return (
    <html lang={locale}>
      <body className="flex items-center flex-col">
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  )
}
