import './globals.css'

import { notFound } from 'next/navigation'
import { useLocale } from 'next-intl'
import { PropsWithChildren } from 'react'

import { Locale } from '@/i18n'
import Providers from 'utils/provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = PropsWithChildren<{
  params: { locale: Locale }
}>

export default function RootLayout({ children, params }: RootLayoutProps) {
  const locale = useLocale()

  if (params.locale !== locale) {
    notFound()
  }

  return (
    <html lang={locale}>
      <body className="flex items-center flex-col">
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
